project:
  type: website
  output-dir: docs

website:
  title: "Tobias M. Holden"
  navbar:
    background: primary
    foreground: light
    left:
      - href: cv.qmd
        text: "CV"
      - text: "Research"
        menu: 
          - research/research_covid.qmd
          - research/research_malaria.qmd
      - blog.qmd
  page-footer: "© Tobias M. Holden 2023"

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

