project:
  type: website
  output-dir: docs

website:
  title: "Tobias M. Holden"
  sidebar:
    background: primary
    style: "floating"
    search: true
    contents: 
      - href: cv.qmd
        text: "CV"
      - section: "Research"
        contents:
          - research/research_covid.qmd
          
          - research/research_malaria.qmd
      - section: "Blogs"
        contents: 
          - blog/coding_fun.qmd
          - section: "Tastes"
            contents: 
              - blog/tastes/reading_list.qmd
              - blog/tastes/reviews.qmd
  page-footer: "© Tobias M. Holden 2023"

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

